include:
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_left-xiao_ble-zmk
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_right-xiao_ble-zmk
# there is no settingsreset (needed) for the XIAO
